#服务启动访问端口
server:
  port: 9950
  
#spring cloud 数据库连接等相关配置
spring:
  jpa:
     generate-ddl: false
#     show-sql: true
#     hibernate:
#        ddl-auto: none
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/mylianxi
     username: root
     password: root
#     platform: h2
#     schema: classpath:schema.sql
#     data: classpath:data.sql  application:    name: interceptor9950
#    #热部署
#  devtools: 
#    restart: 
#      enabled: true
#日志管理
logging:  level:    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
#注册到eureka   
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}